import React, { ComponentProps, PropsWithChildren } from "react";
import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "~/components/ui/sidebar";

import { TRPCReactProvider } from "~/trpc/react";
// import { AppSidebar } from "~/components/AppSidebar";
import { Separator } from "@radix-ui/react-separator";
import { Plus } from "lucide-react";
import { SessionProvider } from "next-auth/react";
import { AppSidebar } from "~/components/app-sidebar";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "~/components/ui/breadcrumb";
import { Button } from "~/components/ui/button";
import { auth } from "~/server/auth";
import { redirect } from "next/navigation";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
function AuthLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body  className="h-screen w-screen">{children}</body>
    </html>
  );
}

export default AuthLayout;
