import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { SidebarProvider } from "~/components/ui/sidebar";

import { TRPCReactProvider } from "~/trpc/react";
// import { AppSidebar } from "~/components/AppSidebar";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function AllProviders({
  children,
  withSidebar,
}: Readonly<{ children: React.ReactNode; withSidebar?: boolean }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <SessionProvider>
            {withSidebar ? (
              <SidebarProvider>{children}</SidebarProvider>
            ) : (
              children
            )}
          </SessionProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
